name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        env:
          TEST_ACCESS_TOKEN: ${{secrets.TEST_ACCESS_TOKEN}}
          TEST_GROUP_ID: ${{secrets.TEST_GROUP_ID}}
        run: |
          cd src
          poetry run pytest -sv
